require(quantmod)
combine=function(x) { fritz=x[,6]; colnames(fritz)=deparse(substitute(x)); fritz }

### ALL ISHARES EQUITY ETFs
getSymbols(c('IVV','EFA','EEM','IWF','IWD','IJH','IWM','IJR','PFF','IWB','DVY','IEMG','USMV','EWJ','IVW','IWR','IEFA'))
getSymbols(c('IVE','EZU','EFAV','IWS','IBB','IWN','HDV','IWO','IWP','IWV','SCZ','IJK','ACWI','IJJ','ITOT','OEF','EEMV'))
getSymbols(c('INDA','EWZ','IJS','FXI','EWG','HEFA','EWY','IJT','ACWV','EWC','IDV','EFV','IXUS','IYW','AAXJ','QUAL'))
getSymbols(c('EWT','IEV','EPP','EFG','MCHI','IYH','EWU','ACWX','MTUM','EWA','IXJ','IOO','EWH','ITB','IHI','HEZU','EWW'))
getSymbols(c('IYE','IXC','IYF','IGE','EWL','IGF','IDU','IYY','IEUR','IUSG','IYC','IGM','ILF','IYK','ITA','IUSV','IYJ'))
getSymbols(c('IPAC','IXN','JKE','IGV','XT','INDY','IWC','EIDO','VLUE','IHF','KXI','IWY','JKD','IHE','EWP','JKG','IYZ'))
getSymbols(c('DGRO','IYM','DSI','IYG','EWS','IYT','HEWJ','HEWG','EWI','SOXX','THD','EZA','KLD','FM','JKL','TUR','IXP'))
getSymbols(c('AIA','IEO','EUFN','ECH','EPHE','EWQ','EWM','ERUS','RING','JKF','URTH','DVYE','EWD','IAT','TOK','RXI','CRBN'))
getSymbols(c('EPU','IEZ','MXI','PICK','JKI','EEMA','JKJ','IXG','JKH','EWN','SIZE','HEEM','EPOL','WOOD','EXI','BKF','ENZL'))
getSymbols(c('IWX','SCJ','JXI','EWK','DVYA','EIRL','EEMS','INTF','JKK','LRGF','IWL','SLVP','JPXN','EIS','IAK','IAI'))
getSymbols(c('IPFF','ICLN','EUSA','HEWU','SMIN','IGN','EWO','IEUS','QAT','EWZS','EDEN','EMIF','JPMV','UAE','EUMV','IVLU'))
getSymbols(c('EFNL','FILL','IELG','EMGF','VEGI','ENOR','EWUS','EWGS','IEIS','ECNS','IEIL','ICOL','HEWP','IMTM','SMLF'))
getSymbols(c('IQLT','MPCT','IESM','HEWY','HEWC','HAUD','AXJV','EEML','CNYA','HEFV','HSCZ','HEWI','HEMV','ESGE')) # ,'ESGD' deleted
getSymbols(c('ISCF','IGRO','ISZE','ACWF','HEWL','KSA','HEUV','DEWJ','EMHZ')) # 'TCHF', deleted
getSymbols(c('HCRF','MATF','HACV')) # 'CNDF', deleted
getSymbols(c('FNCF','INDF')) # 'ERGF','CNSF', deleted 
getSymbols(c('UTLF','DEFA','DEZU','HAWX','HJPX','HEUS','HACW','HEWW'))
# getSymbols(c('ESGD'))

head(do.call(cbind, lapply(list(IXUS,IYW,AAXJ,QUAL,EWT,IEV,EPP,EFG,MCHI,IYH,EWU,ACWX,MTUM,EWA,IXJ,IOO,EWH,ITB,IHI,HEZU,EWW,IYE),combine)))

test=list(IVV,EFA,EEM,IWF,IWD,IJH,IWM,IJR,PFF,IWB,DVY,IEMG,USMV,EWJ,IVW,IWR,IEFA,IVE,EZU,EFAV,IWS,IBB,IWN,HDV,IWO,IWP,IWV,SCZ,IJK,ACWI,IJJ,ITOT,OEF,EEMV,INDA,EWZ,IJS,FXI,EWG,HEFA,EWY,IJT,ACWV,EWC,IDV,EFV,IXUS,IYW,AAXJ,QUAL,EWT,IEV,EPP,EFG,MCHI,IYH,EWU,ACWX,MTUM,EWA,IXJ,IOO,EWH,ITB,IHI,HEZU,EWW,IYE,IXC,IYF,IGE,EWL,IGF,IDU,IYY,IEUR,IUSG,IYC,IGM,ILF,IYK,ITA,IUSV,IYJ,IPAC,IXN,JKE,IGV,XT,INDY,IWC,EIDO,VLUE,IHF,KXI,IWY,JKD,IHE,EWP,JKG,IYZ,DGRO,IYM,DSI,IYG,EWS,IYT,HEWJ,HEWG,EWI,SOXX,THD,EZA,KLD,FM,JKL,TUR,IXP,AIA,IEO,EUFN,ECH,EPHE,EWQ,EWM,ERUS,RING,JKF,URTH,DVYE,EWD,IAT,TOK,RXI,CRBN,EPU,IEZ,MXI,PICK,JKI,EEMA,JKJ,IXG,JKH,EWN,SIZE,HEEM,EPOL,WOOD,EXI,BKF,ENZL,IWX,SCJ,JXI,EWK,DVYA,EIRL,EEMS,INTF,JKK,LRGF,IWL,SLVP,JPXN,EIS,IAK,IAI,IPFF,ICLN,EUSA,HEWU,SMIN,IGN,EWO,IEUS,QAT,EWZS,EDEN,EMIF,JPMV,UAE,EUMV,IVLU,EFNL,FILL,IELG,EMGF,VEGI,ENOR,EWUS,EWGS,IEIS,ECNS,IEIL,ICOL,HEWP,IMTM,SMLF,IQLT,MPCT,IESM,HEWY,HEWC,HAUD,AXJV,EEML,CNYA,HEFV,HSCZ,HEWI,HEMV,ESGE,ISCF,IGRO,ISZE,ACWF,HEWL,KSA,HEUV,DEWJ,EMHZ,HCRF,MATF,HACV,FNCF,INDF,UTLF,DEFA,DEZU,HAWX,HJPX,HEUS,HACW,HEWW)
test=do.call(cbind, lapply(test,combine))
colnames(test)=c('IVV','EFA','EEM','IWF','IWD','IJH','IWM','IJR','PFF','IWB','DVY','IEMG','USMV','EWJ','IVW','IWR','IEFA','IVE','EZU','EFAV','IWS','IBB','IWN','HDV','IWO','IWP','IWV','SCZ','IJK','ACWI','IJJ','ITOT','OEF','EEMV','INDA','EWZ','IJS','FXI','EWG','HEFA','EWY','IJT','ACWV','EWC','IDV','EFV','IXUS','IYW','AAXJ','QUAL','EWT','IEV','EPP','EFG','MCHI','IYH','EWU','ACWX','MTUM','EWA','IXJ','IOO','EWH','ITB','IHI','HEZU','EWW','IYE','IXC','IYF','IGE','EWL','IGF','IDU','IYY','IEUR','IUSG','IYC','IGM','ILF','IYK','ITA','IUSV','IYJ','IPAC','IXN','JKE','IGV','XT','INDY','IWC','EIDO','VLUE','IHF','KXI','IWY','JKD','IHE','EWP','JKG','IYZ','DGRO','IYM','DSI','IYG','EWS','IYT','HEWJ','HEWG','EWI','SOXX','THD','EZA','KLD','FM','JKL','TUR','IXP','AIA','IEO','EUFN','ECH','EPHE','EWQ','EWM','ERUS','RING','JKF','URTH','DVYE','EWD','IAT','TOK','RXI','CRBN','EPU','IEZ','MXI','PICK','JKI','EEMA','JKJ','IXG','JKH','EWN','SIZE','HEEM','EPOL','WOOD','EXI','BKF','ENZL','IWX','SCJ','JXI','EWK','DVYA','EIRL','EEMS','INTF','JKK','LRGF','IWL','SLVP','JPXN','EIS','IAK','IAI','IPFF','ICLN','EUSA','HEWU','SMIN','IGN','EWO','IEUS','QAT','EWZS','EDEN','EMIF','JPMV','UAE','EUMV','IVLU','EFNL','FILL','IELG','EMGF','VEGI','ENOR','EWUS','EWGS','IEIS','ECNS','IEIL','ICOL','HEWP','IMTM','SMLF','IQLT','MPCT','IESM','HEWY','HEWC','HAUD','AXJV','EEML','CNYA','HEFV','HSCZ','HEWI','HEMV','ESGE','ISCF','IGRO','ISZE','ACWF','HEWL','KSA','HEUV','DEWJ','EMHZ','HCRF','MATF','HACV','FNCF','INDF','UTLF','DEFA','DEZU','HAWX','HJPX','HEUS','HACW','HEWW')
saveRDS(test, 'all_iShares_Equity.rds')

### ALL ISHARES BONDS ETFS
# - FIBR
getSymbols(c('AGG','LQD','TIP','HYG','CSJ','SHY','EMB','IEF','MBB','TLT','MUB','CIU','IEI','SHV','FLOT','GOVT','GVI','NEAR','CLY','SUB','SHYG','CRED','TLH','IGOV','STIP','CMF','AGZ','IUSB','ISTB','LEMB','CMBS','IAGG','GBF','NYF','ILTB','IBMF','IBDL','IBCC','HYXU','IBDM','SLQD','IBDK','GNMA','IBDH','IBMG','IBME','IBDN','IBMH','IBMI','IBDB','QLTA','GHYG','IBDJ','IBDC','ISHG','IBDD','IBDO','IBCD','EMHY','IBDF','IBDQ','IBDP','IBMJ','IBMK','IBCE','QLTB','LQDH','HYGH','MEAR','CEMB','ITIP','TFLO','GTIP','ICSH','ICVT','BYLD','QLTC','FALN','HYXE','CLYH','HHYX','EMBH'))
test=list(AGG,LQD,TIP,HYG,CSJ,SHY,EMB,IEF,MBB,TLT,MUB,CIU,IEI,SHV,FLOT,GOVT,GVI,NEAR,CLY,SUB,SHYG,CRED,TLH,IGOV,STIP,CMF,AGZ,IUSB,ISTB,LEMB,CMBS,IAGG,GBF,NYF,ILTB,IBMF,IBDL,IBCC,HYXU,IBDM,SLQD,IBDK,GNMA,IBDH,IBMG,IBME,IBDN,IBMH,IBMI,IBDB,QLTA,GHYG,IBDJ,IBDC,ISHG,IBDD,IBDO,IBCD,EMHY,IBDF,IBDQ,IBDP,IBMJ,IBMK,IBCE,QLTB,LQDH,HYGH,MEAR,CEMB,ITIP,TFLO,GTIP,ICSH,ICVT,BYLD,QLTC,FALN,HYXE,CLYH,HHYX,EMBH)
rm(AGG,LQD,TIP,HYG,CSJ,SHY,EMB,IEF,MBB,TLT,MUB,CIU,IEI,SHV,FLOT,GOVT,GVI,NEAR,CLY,SUB,SHYG,CRED,TLH,IGOV,STIP,CMF,AGZ,IUSB,ISTB,LEMB,CMBS,IAGG,GBF,NYF,ILTB,IBMF,IBDL,IBCC,HYXU,IBDM,SLQD,IBDK,GNMA,IBDH,IBMG,IBME,IBDN,IBMH,IBMI,IBDB,QLTA,GHYG,IBDJ,IBDC,ISHG,IBDD,IBDO,IBCD,EMHY,IBDF,IBDQ,IBDP,IBMJ,IBMK,IBCE,QLTB,LQDH,HYGH,MEAR,CEMB,ITIP,TFLO,GTIP,ICSH,ICVT,BYLD,QLTC,FALN,HYXE,CLYH,HHYX,EMBH)

test=do.call(cbind, lapply(test,combine))
colnames(test)=c('AGG','LQD','TIP','HYG','CSJ','SHY','EMB','IEF','MBB','TLT','MUB','CIU','IEI','SHV','FLOT','GOVT','GVI','NEAR','CLY','SUB','SHYG','CRED','TLH','IGOV','STIP','CMF','AGZ','IUSB','ISTB','LEMB','CMBS','IAGG','GBF','NYF','ILTB','IBMF','IBDL','IBCC','HYXU','IBDM','SLQD','IBDK','GNMA','IBDH','IBMG','IBME','IBDN','IBMH','IBMI','IBDB','QLTA','GHYG','IBDJ','IBDC','ISHG','IBDD','IBDO','IBCD','EMHY','IBDF','IBDQ','IBDP','IBMJ','IBMK','IBCE','QLTB','LQDH','HYGH','MEAR','CEMB','ITIP','TFLO','GTIP','ICSH','ICVT','BYLD','QLTC','FALN','HYXE','CLYH','HHYX','EMBH')
saveRDS(test, 'all_iShares_Bonds.rds')
tail(readRDS('~/ETFconstituentsdaily/all_iShares_Bonds.rds'),1)

### ALL ISHARES COMMODITY ETFS
IAU,SLV,GSG,COMT,CMDT

### ALL POWERSHARES EQUITY ETFS
getSymbols(c('ADRA','ADRD','ADRE','ADRU','PIZ','PIE','DWLV','FXEP','PXR','FXEU','IDLB','PAF','PXF','PDN','PXH','PGJ','PIN','IPKW','PID','FXJP','EELV','EEMO','IDLV','IDMO','IDHQ','PPA','PZD','PYZ','PEZ','PSL','PXI','PFI','PTH','PRN','PTF','PUI','PBE','PKB','PXE','PBJ','PEJ','PBS','PXQ','PXJ','PJP','PMR','PSI','PSJ','PAGG','PBD','PSAU','PIO','KBWB','KBWP','KBWR','PNQI','PSCD','PSCC','PSCE','PSCF','PSCH','PSCI','PSCT','PSCM','PSCU','PHO','PBW','PUW','PKW','PCEF','CNTR','PDP','DWAQ','DWAS','DWTR','PFM','PWB','PWV','PWC','PRF','PRFZ','PGF','PEY','KBWD','PGX','QQQ','EQAL','USLB','EQWS','PXSG','PXSV','EQWM','PXMG','PXMV','EQWL','PXLG','PXLV','SPHB','SPHD','SPLV','SPMO','SPHQ','SPVU','XRLV','XMLV','XSLV','VRP','PZI'))
test=list(ADRA,ADRD,ADRE,ADRU,PIZ,PIE,DWLV,FXEP,PXR,FXEU,IDLB,PAF,PXF,PDN,PXH,PGJ,PIN,IPKW,PID,FXJP,EELV,EEMO,IDLV,IDMO,IDHQ,PPA,PZD,PYZ,PEZ,PSL,PXI,PFI,PTH,PRN,PTF,PUI,PBE,PKB,PXE,PBJ,PEJ,PBS,PXQ,PXJ,PJP,PMR,PSI,PSJ,PAGG,PBD,PSAU,PIO,KBWB,KBWP,KBWR,PNQI,PSCD,PSCC,PSCE,PSCF,PSCH,PSCI,PSCT,PSCM,PSCU,PHO,PBW,PUW,PKW,PCEF,CNTR,PDP,DWAQ,DWAS,DWTR,PFM,PWB,PWV,PWC,PRF,PRFZ,PGF,PEY,KBWD,PGX,QQQ,EQAL,USLB,EQWS,PXSG,PXSV,EQWM,PXMG,PXMV,EQWL,PXLG,PXLV,SPHB,SPHD,SPLV,SPMO,SPHQ,SPVU,XRLV,XMLV,XSLV,VRP,PZI)
test=do.call(cbind, lapply(test,combine))
colnames(test)=c('ADRA','ADRD','ADRE','ADRU','PIZ','PIE','DWLV','FXEP','PXR','FXEU','IDLB','PAF','PXF','PDN','PXH','PGJ','PIN','IPKW','PID','FXJP','EELV','EEMO','IDLV','IDMO','IDHQ','PPA','PZD','PYZ','PEZ','PSL','PXI','PFI','PTH','PRN','PTF','PUI','PBE','PKB','PXE','PBJ','PEJ','PBS','PXQ','PXJ','PJP','PMR','PSI','PSJ','PAGG','PBD','PSAU','PIO','KBWB','KBWP','KBWR','PNQI','PSCD','PSCC','PSCE','PSCF','PSCH','PSCI','PSCT','PSCM','PSCU','PHO','PBW','PUW','PKW','PCEF','CNTR','PDP','DWAQ','DWAS','DWTR','PFM','PWB','PWV','PWC','PRF','PRFZ','PGF','PEY','KBWD','PGX','QQQ','EQAL','USLB','EQWS','PXSG','PXSV','EQWM','PXMG','PXMV','EQWL','PXLG','PXLV','SPHB','SPHD','SPLV','SPMO','SPHQ','SPVU','XRLV','XMLV','XSLV','VRP','PZI')
tail(test)
saveRDS(test, 'all_PowerShares_Equity.rds')


### ALL POWERSHARES BONDS ETFS
getSymbols(c('DSUM','DWIN','PCY','PGHY','PICB','PLW','BAB','PWZ','PHB','PFIG','LDRI','PZA','PZT','PVI'))
test=list(DSUM,DWIN,PCY,PGHY,PICB,PLW,BAB,PWZ,PHB,PFIG,LDRI,PZA,PZT,PVI)
rm(DSUM,DWIN,PCY,PGHY,PICB,PLW,BAB,PWZ,PHB,PFIG,LDRI,PZA,PZT,PVI)
test=do.call(cbind, lapply(test,combine))
colnames(test)=c('DSUM','DWIN','PCY','PGHY','PICB','PLW','BAB','PWZ','PHB','PFIG','LDRI','PZA','PZT','PVI')
tail(test)
saveRDS(test, 'all_PowerShares_Bonds.rds')

### ALL POWERSHARES OTHER ETFS
BKLN,DBA,DBB,DBC,DBE,DGL,DBO,PDBC,DBP,DBS,DBV,UDN,UUP,LALT,PBP,PHDG,PSP,PSR,KBWY


### ALL VANGUARD
getSymbols(c('VIG','VUG','VYM','VV','MGC','MGK','MGV','VOO','VTI','VTV','VXF','VO','VOT','VOE','VB','VBK','VBR','VEU','VSS','VEA','VWO','VGK','VPL','VIGI','VYMI','VXUS','VT','VCR','VDC','VDE','VFH','VHT','VIS','VGT','VAW','VOX','VPU'))
test=list(VIG,VUG,VYM,VV,MGC,MGK,MGV,VOO,VTI,VTV,VXF,VO,VOT,VOE,VB,VBK,VBR,VEU,VSS,VEA,VWO,VGK,VPL,VIGI,VYMI,VXUS,VT,VCR,VDC,VDE,VFH,VHT,VIS,VGT,VAW,VOX,VPU)
test=do.call(cbind, lapply(test,combine))
colnames(test)=c('VIG','VUG','VYM','VV','MGC','MGK','MGV','VOO','VTI','VTV','VXF','VO','VOT','VOE','VB','VBK','VBR','VEU','VSS','VEA','VWO','VGK','VPL','VIGI','VYMI','VXUS','VT','VCR','VDC','VDE','VFH','VHT','VIS','VGT','VAW','VOX','VPU')
saveRDS(test, 'all_Vanguard_Equity.rds')

### ALL VANGUARD BONDS
getSymbols(c('EDV','BIV','VGIT','BLV','VGLT','VMBS','BSV','VGSH','VTIP','BND','VCIT','VCLT','VCSH','VTEB'))
rm(EDV,BIV,VGIT,BLV,VGLT,VMBS,BSV,VGSH,VTIP,BND,VCIT,VCLT,VCSH,VTEB)

### ALL SPDR
getSymbols(c('DIA','ONEK','TWOK','THRK','RSCO','SPY','SLY','MDY','MDYG','MDYV','SPYG','SPYV','SLYG','SLYV','XLY','XLP','XLE','XLF','XLFS','XLV','XLI','XLB','XLRE','XLK','XLU','XITK','MTK','XAR','KBE','XBI','KCE','XHE','XHS','XHB','KIE','XME','XES','XOP','XPH','KRE','XRT','XSD','XSW','XTL','XTN','DGT','CWI','ACIM','MDD','GWX','GWL','HFEZ','FEZ','SMEZ','JPP','JSC','FEU','XINA','EMFT','EMBB','BIK','GXC','GMF','GUR','GML','GMM','EWX','GAF','RBL','IPD','IPS','IPW','IPF','IRY','IPN','IRV','IPK','IST','IPU','SPYD','SDY','EDIV','WDIV','HDWX','DWX','QAUS','QCAN','QEFA','QEMM','QDEU','QJPN','QMEX','QKOR','QESP','QTWN','QGBR','QUS','QWLD','LGLV','ONEV','ONEO','ONEY','SMLV','MMTM','VLU','SPYB','GAL','INKM','RLY','SYE','SYG','SYV','RORO'))
test=list(DIA,ONEK,TWOK,THRK,RSCO,SPY,SLY,MDY,MDYG,MDYV,SPYG,SPYV,SLYG,SLYV,XLY,XLP,XLE,XLF,XLFS,XLV,XLI,XLB,XLRE,XLK,XLU,XITK,MTK,XAR,KBE,XBI,KCE,XHE,XHS,XHB,KIE,XME,XES,XOP,XPH,KRE,XRT,XSD,XSW,XTL,XTN,DGT,CWI,ACIM,MDD,GWX,GWL,HFEZ,FEZ,SMEZ,JPP,JSC,FEU,XINA,EMFT,EMBB,BIK,GXC,GMF,GUR,GML,GMM,EWX,GAF,RBL,IPD,IPS,IPW,IPF,IRY,IPN,IRV,IPK,IST,IPU,SPYD,SDY,EDIV,WDIV,HDWX,DWX,QAUS,QCAN,QEFA,QEMM,QDEU,QJPN,QMEX,QKOR,QESP,QTWN,QGBR,QUS,QWLD,LGLV,ONEV,ONEO,ONEY,SMLV,MMTM,VLU,SPYB,GAL,INKM,RLY,SYE,SYG,SYV,RORO)
test=do.call(cbind, lapply(test,combine))
colnames(test)=c('DIA','ONEK','TWOK','THRK','RSCO','SPY','SLY','MDY','MDYG','MDYV','SPYG','SPYV','SLYG','SLYV','XLY','XLP','XLE','XLF','XLFS','XLV','XLI','XLB','XLRE','XLK','XLU','XITK','MTK','XAR','KBE','XBI','KCE','XHE','XHS','XHB','KIE','XME','XES','XOP','XPH','KRE','XRT','XSD','XSW','XTL','XTN','DGT','CWI','ACIM','MDD','GWX','GWL','HFEZ','FEZ','SMEZ','JPP','JSC','FEU','XINA','EMFT','EMBB','BIK','GXC','GMF','GUR','GML','GMM','EWX','GAF','RBL','IPD','IPS','IPW','IPF','IRY','IPN','IRV','IPK','IST','IPU','SPYD','SDY','EDIV','WDIV','HDWX','DWX','QAUS','QCAN','QEFA','QEMM','QDEU','QJPN','QMEX','QKOR','QESP','QTWN','QGBR','QUS','QWLD','LGLV','ONEV','ONEO','ONEY','SMLV','MMTM','VLU','SPYB','GAL','INKM','RLY','SYE','SYG','SYV','RORO')
saveRDS(test, 'all_SPDR_Equity.rds')

### ALL SPDR BONDS
getSymbols(c('JNK','IJNK','SJNK','CJNK','ITR','FLRN','LWC','SCPB','SIPE','TIPX','BIL','ITE','TLO','SST','IPE','MBG','BNDS','DWFI',
getSymbols(c('CXA','TFI','INY','SHM','HYMB','EBND','IBND','BWX','BWZ','EMCD','WIP')) # 'BABS'
rm(JNK,IJNK,SJNK,CJNK,ITR,FLRN,LWC,SCPB,SIPE,TIPX,BIL,ITE,TLO,SST,IPE,MBG,BNDS,DWFI,BABS,CXA,TFI,INY,SHM,HYMB,EBND,IBND,BWX,BWZ,EMCD,WIP)
warnings()

### ALL EQUITY
P1=readRDS('all_PowerShares_Equity.rds')
P2=readRDS('all_iShares_Equity.rds')
P3=readRDS('all_SPDR_Equity.rds')
P4=readRDS('all_Vanguard_Equity.rds')
P=cbind(P1,P2,P3,P4)
P=P[ , apply(P, 2, function(x) !any(is.na(x)))]
saveRDS(P, 'all_Equity.rds')
P=as.data.frame(P)
ncol(P)
write.csv(P, 'ALL_naomit.csv', row.names = T)

saveRDS(P, 'all_Equity_naomit.rds')

